service: hello-world

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  logRetentionDays: 10
  timeout: 5
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: "*"

functions:
  helloGet:
    handler: dist/src/handlers/hello-get-handler.default
    iamRoleStatementsName: hello-get-iam-role
    events:
      - http:
          path: helloMethod
          method: get
          # cors: true not needed for a GET as browsers do not issue pre-flight OPTIONS requests for GETS or POSTS.
  helloResource:
    handler: dist/src/handlers/hello-resource-handler.default
    iamRoleStatementsName: hello-resource-iam-role
    events:
      - http:
          path: helloResource
          method: get
          # cors: true not needed for a GET as browsers do not issue pre-flight OPTIONS requests for GETS or POSTS.
      - http:
          path: helloResource/{routeArgs+}
          method: any
          cors: true
